site_name: Lehrplan Ontology
#theme: readthedocs
theme: mkdocs

nav:
  - Start: index.md
  - Einführung: introduction.md
  - Ontologien: ontology.md
  - Aufbau: structure.md
  - Patterns: patterns.md
  - Verwendung: usage.md
  - Über uns: about.md

#  - Versions: versions.md
#  - Contributing: contributing.md
#  - Contact: contact.md


plugins:
  - d2