site_name: Lehrplan Ontology
#theme: readthedocs
#theme: mkdocs
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  palette:
    primary: custom
  font:
    text: Barlow
  features:
#    - navigation.tabs
#    - navigation.sections
    - navigation.path

nav:
  - Start: index.md
#  - start: index.en.md

  - Ontologien allgemein: ontology.md

  - intro: introduction.md
#  - intro: introduction.en.md

  - structure: structure.md

  - Beispiele: patterns.md

  - SPARQL-Abfragen: sparql.md

  - Verwendung: usage.md

  - Über uns: about.md

#  - Versions: versions.md
#  - Contributing: contributing.md
#  - Contact: contact.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      preserve_tabs: true
  - md_in_html
  - pymdownx.snippets
  - admonition
  - pymdownx.details


      

plugins:
  - d2
  - search
  - ontoink
#  - privacy
  - i18n:
      default_language: 'de'
      languages:
        de: "Deutsch"
        en: "English"
#      no_translation:
#        en: "This page isn't translated to English."
#        de: "Diese Seite wurde nicht auf Deutsch übersetzt."
      translate_nav:
        de:
          start: "Start"
          intro: "Konzeptuelle Grundlagen"
          structure: "Ontologie-Modell"
        en:
          start: "Home"
          intro: "Conceptual Overview"
          structure: "Ontology Structure"

extra_css:
  - extra.css

extra:
  alternate:
    - name: "Deutsch"
      link: ""
      lang: de

    - name: "English"
      link: "index.en/"
      lang: en

repo_url: https://github.com/FWU-DE/lehrplan-ontologie